#!/bin/bash

# exit on error
set -e

# check if running on mac
running_on_mac=0
if [ "$(uname)" == "Darwin" ]
then
    running_on_mac=1
fi

# parse command line args
show_help=0
reprovision=0
dockerup_action=""
dockerup_file="./Dockerupfile"
while [[ $# > 1 ]]
do
    key="$1"
    shift

    case $key in
    -h|--help)
        show_help=1
        ;;
    -r|--reprovision)
        reprovision=1
        ;;
    -f|--file)
        dockerup_file="$1"
        shift
        ;;
    start)
        dockerup_action="start"
        ;;
    stop)
        dockerup_action="stop"
        ;;
    restart)
        dockerup_action="restart"
        ;;
    status)
        dockerup_action="status"
        ;;
    *)
        # unknown option
        show_help=1
        ;;
    esac
done

# show help
if [ "$show_help" == "1" ] || [ "$dockerup_action" == "" ]
then
    echo "Wrapper for running Docker based development environments with Chef and Berkshelf"
    echo "based provisioning. Reads config from the 'Dockerupfile' in your project root folder."
    echo
    echo "Usage: dockerup ACTION [OPTIONS]"
    echo
    echo "Where ACTION has to be one of:"
    echo "  start                           Start the container"
    echo "  stop                            Stop the container"
    echo "  restart                         Restart the container"
    echo "  status                          Show status information for the container"
    echo
    echo "And where OPTIONS can be:"
    echo "  -h, --help                      Show this help"
    echo "  -r, --reprovision               Force to run provisioning, also when caontainer was"
    echo "                                  already provisioned before"
    echo "  -f, --file DOCKERUP_FILE        Pass path to 'Dockerupfile' to be used, default is"
    echo "                                  './Dockerupfile'"
    echo
    echo "Examples:"
    echo "  dockerup start                  Start the container as configured in './Dockerupfile'"
    echo "  dockerup start --reprovision    Start and reprovision the container"
    echo "  dockerup stop                   Stop the container"
    echo "  dockerup restart                Restart the container"
    echo "  dockerup restart --reprovision  Restart and reprovision the container"    
    echo "  dockerup status                 Show status information for the container"
    exit 0
fi


