#!/bin/bash

# exit on error
set -e

# parse command line args
showhelp=0
reprovision=0
dockerupaction=""
dockerupfile="./Dockerupfile"
while [[ $# > 1 ]]
do
    key="$1"
    shift

    case $key in
    -h|--help)
        showhelp=1
        ;;
    -r|--reprovision)
        reprovision=1
        ;;
    -f|--file)
        dockerupfile="$1"
        shift
        ;;
    start)
        dockerupaction="start"
        ;;
    stop)
        dockerupaction="stop"
        ;;
    restart)
        dockerupaction="restart"
        ;;
    status)
        dockerupaction="status"
        ;;
    *)
        # unknown option
        showhelp=1
        ;;
    esac
done

# show help
if [ "$showhelp" = "1" ] || [ "$dockerupaction" = "" ]
then
    echo "Wrapper for running Docker based development environments with Chef and Berkshelf"
    echo "based provisioning. Reads config from the 'Dockerupfile' in your project root folder."
    echo
    echo "Usage: dockerup ACTION [OPTIONS]"
    echo
    echo "Where ACTION has to be one of:"
    echo "  start                           Start the container"
    echo "  stop                            Stop the container"
    echo "  restart                         Restart the container"
    echo "  status                          Show status information"
    echo
    echo "And where OPTIONS can be:"
    echo "  -h, --help                      Show this help"
    echo "  -r, --reprovision               Force reprovisioning, also when caontainer was"
    echo "                                  already provisioned before"
    echo "  -f, --file DOCKERUPFILE         Pass path to 'Dockerupfile' to be used, default"
    echo "                                  is './Dockerupfile'"
    echo
    echo "Examples:"
    echo "  dockerup start                  Start the container as configured in './Dockerupfile'"
    echo "  dockerup start --reprovision    Start and reprovision the container"
    echo "  dockerup stop                   Stop the container"
    echo "  dockerup restart                Restart the container"
    echo "  dockerup restart --reprovision  Restart and reprovision the container"    
    echo "  dockerup status                 Show status information for container"
    exit 0
fi
