#!/bin/bash

# create /tugger/etc_hosts_extra
if ! test -e /tugger/etc_hosts_extra
then
    echo "127.0.0.1 localhost" > /tugger/etc_hosts_extra
fi

# fix permissions of /etc/resolv.conf
chmod a+r /etc/resolv.conf

# set timezone
if test -e /tugger/timezone
then
    cat /tugger/timezone > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
fi

# run provisioning
/bin/bash /tugger/lib/tugger-container-init/provision >> /tugger/init.log 2>&1

# append content from /tugger/etc_hosts_extra to /etc/hosts
echo >> /etc/hosts
cat /tugger/etc_hosts_extra >> /etc/hosts

# append content from /tugger/etc_hosts_other_tugger_containers to /etc/hosts
if test -e /tugger/etc_hosts_other_tugger_containers
then
    echo >> /etc/hosts
    cat /tugger/etc_hosts_other_tugger_containers >> /etc/hosts
fi

# run init script from tugger-stack
/bin/bash /tugger/tugger-stack/init >> /tugger/init.log 2>&1

# keep container running forever (or until it is being stopped)
touch /tugger/init-completed.touch >> /tugger/init.log 2>&1
sleep infinity
