#!/bin/bash

# source tugger file
source /tugger/Tuggerfile

# set variables
reprovision=0
recreate_berksfile_lock=0
if test -e /tugger/reprovision.touch >/dev/null
then
    reprovision=1
fi
if test -e /tugger/recreate-berksfile-lock.touch >/dev/null
then
    recreate_berksfile_lock=1
fi

# run chef-solo / berkshelf provisioning
if ! test -e /tugger/chef-completed.touch >/dev/null || [ "$reprovision" = "1" ]
then
    echo "Updating packages..."
    apt-get -y update
    apt-get -y upgrade
    apt-get -y install python
    echo "Running chef-solo / berkshelf provisioning..."
    rm -rf /chef
    cp -r -Pa /tugger/tugger-stack /chef
    cd /chef
    if [ "$recreate_berksfile_lock" = "1" ]
    then
        rm -f Berksfile.lock
    fi
    if [ "$chef_json_override" != "" ] && (echo "$chef_json_override" | grep --silent "{")
    then
        mv chef.json chef_orig.json
        echo "$chef_json_override" > chef_override.json
        /usr/bin/python2 /tugger/lib/tugger-container-init/json-merge.py chef_orig.json chef_override.json > chef.json
    fi
    /opt/chef/embedded/bin/berks vendor /chef/cookbooks
    chef-solo -c "/chef/chef.rb" -j "/chef/chef.json"
    echo "Chef-solo / berkshelf provisioning completed."
    touch /tugger/chef-completed.touch
fi
